-- Active: 1728681291059@@127.0.0.1@3306@TP3SolisJuanEjercicio2
--  DROP DATABASE IF EXISTS TP3SolisJuanEjercicio2;
--  Juan, usé la sentencia de arriba para no tener que borrar a cada rato las tablas porque tuve muchos problemas
--  con el uso de check y la versión de MariaDB.

CREATE DATABASE TP3SolisJuanEjercicio2;
USE TP3SolisJuanEjercicio2;
CREATE TABLE LOCALIDAD (
    `COD_LOCALIDAD` INT(30) NOT NULL,
    `NOMBRE` CHAR(20) NOT NULL,
    PRIMARY KEY (`COD_LOCALIDAD`)
);

CREATE TABLE PUB (
    `COD_PUB` INT NOT NULL,
    `NOMBRE` CHAR(40) NOT NULL,
    `LICENCIA_FISCAL` CHAR(30) NOT NULL,
    `DOMICILIO` CHAR(20) NOT NULL,
    `FECHA_APERTURA` DATE NOT NULL,
    `HORARIO` CHAR(5) NOT NULL CHECK (`HORARIO` IN ('HOR1', 'HOR2', 'HOR3')),
    `COD_LOCALIDAD` INT(30) NOT NULL,
    PRIMARY KEY (`COD_PUB`),
    FOREIGN KEY (`COD_LOCALIDAD`) REFERENCES `LOCALIDAD` (`COD_LOCALIDAD`)
);

CREATE TABLE TITULO (
    `DNI_TITULAR` CHAR(8) NOT NULL,
    `NOMBRE` CHAR(20) NOT NULL,
    `DOMICILIO` CHAR(30),
    `COD_PUB` INT NOT NULL,
    PRIMARY KEY (`DNI_TITULAR`),
    FOREIGN KEY (`COD_PUB`) REFERENCES `PUB` (`COD_PUB`)
);

CREATE TABLE EMPLEADO (
    `DNI_EMPLEADO` CHAR(8) NOT NULL,
    `NOMBRE` CHAR(20) NOT NULL,
    `DOMICILIO` CHAR(30) NOT NULL,
    PRIMARY KEY (`DNI_EMPLEADO`)
);

CREATE TABLE EXISTENCIAS (
    `COD_ARTICULO` CHAR(8) NOT NULL,
    `NOMBRE` CHAR(20) NOT NULL,
    `CANTIDAD` INT NOT NULL,
    `PRECIO` DECIMAL(10, 2) NOT NULL CHECK (`PRECIO` != 0),
    `COD_PUB` INT NOT NULL,
    PRIMARY KEY (`COD_ARTICULO`),
    FOREIGN KEY (`COD_PUB`) REFERENCES `PUB` (`COD_PUB`)
);

CREATE TABLE PUB_EMPLEADO (
    `COD_PUB` INT NOT NULL,
    `DNI_EMPLEADO` CHAR(8) NOT NULL,
    `FUNCION` CHAR(20) NOT NULL CHECK (`FUNCION` IN ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA')),
    FOREIGN KEY (`COD_PUB`) REFERENCES `PUB` (`COD_PUB`),
    FOREIGN KEY (`DNI_EMPLEADO`) REFERENCES `EMPLEADO` (`DNI_EMPLEADO`),
    PRIMARY KEY (`COD_PUB`, `DNI_EMPLEADO`)
);
