DROP DATABASE IF EXISTS TP4_SOLIS;
CREATE DATABASE TP4_SOLIS;
USE TP4_SOLIS;

CREATE TABLE COMPLEJOS (
    COD_COMPLEJO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(150),
    CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(20),
    HORARIO VARCHAR(50)
);

CREATE TABLE TIPOS (
	COD_TIPO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR (50)
);

CREATE TABLE SALAS (
    COD_SALA INT AUTO_INCREMENT PRIMARY KEY,
    COD_COMPLEJO INT,
    COD_TIPO INT,
    CAPACIDAD INT,
    FOREIGN KEY (COD_COMPLEJO) REFERENCES COMPLEJOS(COD_COMPLEJO),
    FOREIGN KEY (COD_TIPO) REFERENCES TIPOS(COD_TIPO)
);

CREATE TABLE ASIENTOS (
    COD_ASIENTO INT AUTO_INCREMENT PRIMARY KEY,
    COD_SALA INT,
    FILA CHAR(1),
    NUMERO INT,
    DISPONIBILIDAD BOOLEAN NULL DEFAULT NULL,
    FOREIGN KEY (COD_SALA) REFERENCES SALAS(COD_SALA),
    UNIQUE (COD_SALA, FILA, NUMERO)
);

CREATE TABLE PELICULA (
    COD_PELICULA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    FECHA DATE,
    HORA TIME,
    CALIFICACION VARCHAR(10)
);

CREATE TABLE PRECIOS_ESPECTACULOS (
    COD_PELICULA INT,
    COD_COMPLEJO INT,
    COD_SALA INT,
    PRECIO DECIMAL(10, 2),
    PRIMARY KEY (COD_PELICULA, COD_COMPLEJO, COD_SALA),
    FOREIGN KEY (COD_PELICULA) REFERENCES PELICULA(COD_PELICULA),
    FOREIGN KEY (COD_COMPLEJO) REFERENCES COMPLEJOS(COD_COMPLEJO),
    FOREIGN KEY (COD_SALA) REFERENCES SALAS(COD_SALA)
);

CREATE TABLE ESPECTADORES (
    COD_ESPECTADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(150),
    TELEFONO VARCHAR(20),
    CIUDAD VARCHAR(50),
    NTARJETA VARCHAR(20) UNIQUE
);

CREATE TABLE ENTRADAS (
    COD_ENTRADA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    HORA TIME,
    COD_SALA INT,
    COD_ASIENTO INT,
    COD_TIPO INT,
    COD_PELICULA INT,
    COD_ESPECTADOR INT,
    FOREIGN KEY (COD_SALA) REFERENCES SALAS(COD_SALA),
    FOREIGN KEY (COD_ASIENTO) REFERENCES ASIENTOS(COD_ASIENTO),
    FOREIGN KEY (COD_TIPO) REFERENCES TIPOS(COD_TIPO),
    FOREIGN KEY (COD_PELICULA) REFERENCES PELICULA(COD_PELICULA),
    FOREIGN KEY (COD_ESPECTADOR) REFERENCES ESPECTADORES(COD_ESPECTADOR)
);


ALTER TABLE ESPECTADORES ADD COLUMN GENERO VARCHAR(10) CHECK (GENERO IN ('M', 'F', "OTRO"));
ALTER TABLE ESPECTADORES ADD COLUMN EDAD INT CHECK (EDAD >= 18);
ALTER TABLE ESPECTADORES ADD COLUMN TIPO_DE_PAGO VARCHAR(15) CHECK (TIPO_DE_PAGO IN ('DEBITO', 'CREDITO', 'EFECTIVO', 'TRANSFERENCIA'));
ALTER TABLE COMPLEJOS 
ADD CONSTRAINT codigo_ciudad CHECK (CIUDAD IN ('CABA', 'SAN ISIDRO', 'PILAR'));

INSERT INTO pelicula (NOMBRE, FECHA, HORA, CALIFICACION) VALUES ('Batman', '2021-10-10', '20:00:00', 'ATP');